SET C(CCC)  'Countries in the simulation'    
/                                            
NORWAY                                       
DENMARK                                      
FINLAND                                      
GERMANY                                      
NETHERLANDS                                  
SWEDEN                   
ESTONIA                                      
LATVIA                                       
LITHUANIA                                    
POLAND                                       
BELGIUM                                      
FRANCE                                       
ITALY                                        
SWITZERLAND                                  
AUSTRIA                                      
CZECH_REPUBLIC                               
SPAIN                                                                                                            
/;                                           

