PARAMETER DISCOST_H(AAA)  'Cost of heat distribution (Money/MWh)'     
* Areas merged, average values used                                   
/                                                                     
DK1_A                                                             2   
                                                                      
/;                                                                    
DISCOST_H(AAA) = 2;                                                   
