PARAMETER EXPANSION_RENEWABLE(YYY,RRR,TECH_GROUP,GROWTHMODE) "Expansion rates for renewable technologies (MW)"                                             
                                                                                                                                                           
/                                                                                                                                                          
2040                                                                                                           .    DK1  .    SOLARPV .    Y_FIRST_CAP 1000
2040                                                                                                           .    DK1  .    SOLARPV .    Y_LIN_ADD   100 
2040                                                                                                           .    DK1  .    SOLARPV .    Y_EXP_ADD   0.25
2050                                                                                                           .    DK1  .    SOLARPV .    Y_FIRST_CAP 2000
2050                                                                                                           .    DK1  .    SOLARPV .    Y_LIN_ADD   100 
2050                                                                                                           .    DK1  .    SOLARPV .    Y_EXP_ADD   0.25
                                                                                                                                                           
2040                                                                                                           .    DK2  .    SOLARPV .    Y_FIRST_CAP 1000
2040                                                                                                           .    DK2  .    SOLARPV .    Y_LIN_ADD   100 
2040                                                                                                           .    DK2  .    SOLARPV .    Y_EXP_ADD   0.25
2050                                                                                                           .    DK2  .    SOLARPV .    Y_FIRST_CAP 2000
2050                                                                                                           .    DK2  .    SOLARPV .    Y_LIN_ADD   100 
2050                                                                                                           .    DK2  .    SOLARPV .    Y_EXP_ADD   0.25
/;                                                                                                                                                         
