SET FFF  'Hydrogen-Fuels'
/                        
BIOMETHANE               
HYDROGEN                 
IMPORT_H2                
NATGAS_CCS               
THERMGAS_H2              
BIOGAS_H2                
/;                       
ACRONYMS                 
BIOMETHANE               
HYDROGEN                 
IMPORT_H2                
THERMGAS_H2              
BIOGAS_H2                
;                        
