PARAMETER PROCEXIMKAPFX(YYY,IAAAE,IAAAI,PROC) "Existing Capacity of PROCEXIM (U/h)"
                                                                                   
/                                                                                  
                                                                                   
/                                                                                  
;                                                                                  
