SET PROCSOURCE(PROC) "Start PROC (no trace entering)"
/                                                    
CO2_Source_Biogen                                    
CO2_Source_DAC                                       
CO2_Source_Fossil                                    
Road_Diesel_Source                                   
HydrogenSource_MWh                                   
Jet_Source                                           
Marine_Diesel_Source                                 
LNG_Source                                           
Straw_Source                                         
Wood_Source                                          
Manure_Source                                        
Import_Hydrogen                                      
Import_Methanol                                      
Import_Ammonia                                       
Import_FT                                            
/;                                                   
