PARAMETER MINFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"                                                                          
/                                                                                                                                                                    
                                                                                                                                                                     
*2050                                                                                        .    AUSTRIA        .    RoadBuffer .    ROADFLOW 6231272.72727273      
*2050                                                                                        .    BELGIUM        .    RoadBuffer .    ROADFLOW 4673454.54545455      
*2050                                                                                        .    BULGARIA       .    RoadBuffer .    ROADFLOW 3226909.09090909      
*2050                                                                                        .    CROATIA        .    RoadBuffer .    ROADFLOW 1446545.45454545      
*2050                                                                                        .    CYPRUS         .    RoadBuffer .    ROADFLOW 222545.454545455      
*2050                                                                                        .    CZECH_REPUBLIC .    RoadBuffer .    ROADFLOW 6342545.45454545      
*2050                                                                                        .    DENMARK        .    RoadBuffer .    ROADFLOW 5229818.18181818      
*2050                                                                                        .    ESTONIA        .    RoadBuffer .    ROADFLOW 778909.090909091      
*2050                                                                                        .    FINLAND        .    RoadBuffer .    ROADFLOW 6453818.18181818      
*2050                                                                                        .    FRANCE         .    RoadBuffer .    ROADFLOW 46178181.8181818      
*2050                                                                                        .    GERMANY        .    RoadBuffer .    ROADFLOW 46178181.8181818      
*2050                                                                                        .    GREECE         .    RoadBuffer .    ROADFLOW 4228363.63636364      
*2050                                                                                        .    HUNGARY        .    RoadBuffer .    ROADFLOW 6787636.36363636      
*2050                                                                                        .    IRELAND        .    RoadBuffer .    ROADFLOW 12462545.4545455      
*2050                                                                                        .    ITALY          .    RoadBuffer .    ROADFLOW 26037818.1818182      
*2050                                                                                        .    LATVIA         .    RoadBuffer .    ROADFLOW 1669090.90909091      
*2050                                                                                        .    LITHUANIA      .    RoadBuffer .    ROADFLOW 2448000               
*2050                                                                                        .    LUXEMBOURG     .    RoadBuffer .    ROADFLOW 2114181.81818182      
*2050                                                                                        .    MALTA          .    RoadBuffer .    ROADFLOW 1335272.72727273      
*2050                                                                                        .    NETHERLANDS    .    RoadBuffer .    ROADFLOW 12017454.5454545      
*2050                                                                                        .    NORWAY         .    RoadBuffer .    ROADFLOW 8901818.18181818      
*2050                                                                                        .    POLAND         .    RoadBuffer .    ROADFLOW 29598545.4545455      
*2050                                                                                        .    PORTUGAL       .    RoadBuffer .    ROADFLOW 4562181.81818182      
*2050                                                                                        .    ROMANIA        .    RoadBuffer .    ROADFLOW 4673454.54545455      
*2050                                                                                        .    SLOVAKIA       .    RoadBuffer .    ROADFLOW 4562181.81818182      
*2050                                                                                        .    SLOVENIA       .    RoadBuffer .    ROADFLOW 1780363.63636364      
*2050                                                                                        .    SPAIN          .    RoadBuffer .    ROADFLOW 26371636.3636364      
*2050                                                                                        .    SWEDEN         .    RoadBuffer .    ROADFLOW 8790545.45454546      
*2050                                                                                        .    SWITZERLAND    .    RoadBuffer .    ROADFLOW 5563636.36363636      
                                                                                                                                                                     
2050                                                                                         .    BELGIUM        .    SeaBuffer  .    SEAFLOW  193770901.487115      
2050                                                                                         .    BULGARIA       .    SeaBuffer  .    SEAFLOW  1917703.06956334      
2050                                                                                         .    CROATIA        .    SeaBuffer  .    SEAFLOW  111775.589567662      
2050                                                                                         .    DENMARK        .    SeaBuffer  .    SEAFLOW  19935701.2423326      
2050                                                                                         .    ESTONIA        .    SeaBuffer  .    SEAFLOW  8562950.18446756      
2050                                                                                         .    FINLAND        .    SeaBuffer  .    SEAFLOW  8359408.0554494       
2050                                                                                         .    FRANCE         .    SeaBuffer  .    SEAFLOW  43206020.2389962      
2050                                                                                         .    GERMANY        .    SeaBuffer  .    SEAFLOW  62846856.172859       
2050                                                                                         .    GREECE         .    SeaBuffer  .    SEAFLOW  52881021.6218352      
2050                                                                                         .    IRELAND        .    SeaBuffer  .    SEAFLOW  4446133.83881984      
2050                                                                                         .    ITALY          .    SeaBuffer  .    SEAFLOW  57343449.2638501      
2050                                                                                         .    LATVIA         .    SeaBuffer  .    SEAFLOW  6743454.17202171      
2050                                                                                         .    LITHUANIA      .    SeaBuffer  .    SEAFLOW  4415280.11251424      
2050                                                                                         .    NETHERLANDS    .    SeaBuffer  .    SEAFLOW  299467596.888796      
2050                                                                                         .    POLAND         .    SeaBuffer  .    SEAFLOW  7025863.38066032      
2050                                                                                         .    PORTUGAL       .    SeaBuffer  .    SEAFLOW  19023040.3346636      
2050                                                                                         .    ROMANIA        .    SeaBuffer  .    SEAFLOW  1004886.73948449      
2050                                                                                         .    SLOVENIA       .    SeaBuffer  .    SEAFLOW  4099955.42664001      
2050                                                                                         .    SPAIN          .    SeaBuffer  .    SEAFLOW  165473213.094186      
2050                                                                                         .    SWEDEN         .    SeaBuffer  .    SEAFLOW  60502072.9693085      
2050                                                                                         .    NORWAY         .    SeaBuffer  .    SEAFLOW  65705288.5909496      
                                                                                                                                                                     
*2050                                                                                        .    AUSTRIA        .    AirBuffer  .    AIRFLOW  18469762.1306695      
*2050                                                                                        .    BELGIUM        .    AirBuffer  .    AIRFLOW  39311123.2865205      
*2050                                                                                        .    BULGARIA       .    AirBuffer  .    AIRFLOW  6189666.80080998      
*2050                                                                                        .    CROATIA        .    AirBuffer  .    AIRFLOW  4043454.59439466      
*2050                                                                                        .    CZECH_REPUBLIC .    AirBuffer  .    AIRFLOW  8643686.53784498      
*2050                                                                                        .    DENMARK        .    AirBuffer  .    AIRFLOW  25829378.6207233      
*2050                                                                                        .    ESTONIA        .    AirBuffer  .    AIRFLOW  1442330.17059186      
*2050                                                                                        .    FINLAND        .    AirBuffer  .    AIRFLOW  15946502.0788397      
*2050                                                                                        .    FRANCE         .    AirBuffer  .    AIRFLOW  159050623.434372      
*2050                                                                                        .    GERMANY        .    AirBuffer  .    AIRFLOW  235912862.995356      
*2050                                                                                        .    GREECE         .    AirBuffer  .    AIRFLOW  26110950.9469185      
*2050                                                                                        .    HUNGARY        .    AirBuffer  .    AIRFLOW  5704024.55644488      
*2050                                                                                        .    IRELAND        .    AirBuffer  .    AIRFLOW  23277309.5377299      
*2050                                                                                        .    ITALY          .    AirBuffer  .    AIRFLOW  92811116.6686765      
*2050                                                                                        .    LATVIA         .    AirBuffer  .    AIRFLOW  3316450.14162426      
*2050                                                                                        .    LITHUANIA      .    AirBuffer  .    AIRFLOW  2601217.2263729       
*2050                                                                                        .    LUXEMBOURG     .    AirBuffer  .    AIRFLOW  13316627.1722478      
*2050                                                                                        .    NETHERLANDS    .    AirBuffer  .    AIRFLOW  99442742.6962143      
*2050                                                                                        .    POLAND         .    AirBuffer  .    AIRFLOW  20431892.1425041      
*2050                                                                                        .    PORTUGAL       .    AirBuffer  .    AIRFLOW  30184501.756741       
*2050                                                                                        .    ROMANIA        .    AirBuffer  .    AIRFLOW  8763862.39470992      
*2050                                                                                        .    SLOVAKIA       .    AirBuffer  .    AIRFLOW  998674.33856345       
*2050                                                                                        .    SLOVENIA       .    AirBuffer  .    AIRFLOW  603224.988055188      
*2050                                                                                        .    SPAIN          .    AirBuffer  .    AIRFLOW  123514522.26616       
*2050                                                                                        .    SWEDEN         .    AirBuffer  .    AIRFLOW  20597686.740311       
*2050                                                                                        .    NORWAY         .    AirBuffer  .    AIRFLOW  22094635.1778734      
*2050                                                                                        .    SWITZERLAND    .    AirBuffer  .    AIRFLOW  29636406.1760501      
                                                                                                                                                                     
/;                                                                                                                                                                   
                                                                                                                                                                     
MINFLOW('2030',C,PROC,FLOW)$(MINFLOW('2050',C,PROC,FLOW)) = 0.1*MINFLOW('2050',C,PROC,FLOW);                                                                         
MINFLOW('2040',C,PROC,FLOW)$(MINFLOW('2050',C,PROC,FLOW)) = 0.5*MINFLOW('2050',C,PROC,FLOW);                                                                         
