PARAMETER PROCKAP_RETRO_SURVIVAL(YYY,PROC) "fraction of  capacity with vessels still technically operational in a given year (eligible for retrofit use only)"                                   
/                                                                                                                                                                                                
2030                                                                                                                                                           .    Diesel_Legacy_Existing 1     
2040                                                                                                                                                           .    Diesel_Legacy_Existing 0.735
2050                                                                                                                                                           .    Diesel_Legacy_Existing 0.269
                                                                                                                                                                                                 
2030                                                                                                                                                           .    Diesel_Tanker_Existing 1     
2040                                                                                                                                                           .    Diesel_Tanker_Existing 0.694
2050                                                                                                                                                           .    Diesel_Tanker_Existing 0.250 
                                                                                                                                                                                                 
2030                                                                                                                                                           .    LNG_Tanker_Existing    1     
2040                                                                                                                                                           .    LNG_Tanker_Existing    0.699
2050                                                                                                                                                           .    LNG_Tanker_Existing    0.252 
                                                                                                                                                                                                 
/;                                                                                                                                                                                               
                                                                                                                                                                                                 
                                                                                                                                                                                                 
                                                                                                                                                                                                 
                                                                                                                                                                                                 
                                                                                                                                                                                                 
                                                                                                                                                                                                 
                                                                                                                                                                                                 
