SCALAR OPTIFLOW_SUBSEA_REL_INCR  'Increase in PROCINVCOST for the subsea share of a transport pipeline (relative increase from base)';
                                                                                                                                 
OPTIFLOW_SUBSEA_REL_INCR=2;                                                                                                           
