PARAMETER MAXFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"                                                                                              
/                                                                                                                                                                                        
2030                                                                                                                   .    AL_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 1822000  
2030                                                                                                                   .    AT_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 7721000  
2030                                                                                                                   .    BE_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 47612000 
2030                                                                                                                   .    BA_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 1641000  
2030                                                                                                                   .    BG_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 5500000  
2030                                                                                                                   .    HR_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 3276900  
2030                                                                                                                   .    CY_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 4001000  
2030                                                                                                                   .    CZ_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 49609000 
2030                                                                                                                   .    DK011_A .    Manure_Source .    BIOMASS_FLOW_MANURE 5242700  
2030                                                                                                                   .    DK012_A .    Manure_Source .    BIOMASS_FLOW_MANURE 7695400  
2030                                                                                                                   .    DK013_A .    Manure_Source .    BIOMASS_FLOW_MANURE 4294700  
2030                                                                                                                   .    DK014_A .    Manure_Source .    BIOMASS_FLOW_MANURE 8645800  
2030                                                                                                                   .    DK021_A .    Manure_Source .    BIOMASS_FLOW_MANURE 8018400  
2030                                                                                                                   .    DK022_A .    Manure_Source .    BIOMASS_FLOW_MANURE 734900   
2030                                                                                                                   .    DK031_A .    Manure_Source .    BIOMASS_FLOW_MANURE 531700   
2030                                                                                                                   .    DK032_A .    Manure_Source .    BIOMASS_FLOW_MANURE 449700   
2030                                                                                                                   .    DK041_A .    Manure_Source .    BIOMASS_FLOW_MANURE 39600    
2030                                                                                                                   .    DK042_A .    Manure_Source .    BIOMASS_FLOW_MANURE 2336500  
2030                                                                                                                   .    DK050_A .    Manure_Source .    BIOMASS_FLOW_MANURE 5589500  
2030                                                                                                                   .    EE_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 8100000  
2030                                                                                                                   .    FI193_A .    Manure_Source .    BIOMASS_FLOW_MANURE 566100   
2030                                                                                                                   .    FI194_A .    Manure_Source .    BIOMASS_FLOW_MANURE 397600   
2030                                                                                                                   .    FI195_A .    Manure_Source .    BIOMASS_FLOW_MANURE 397600   
2030                                                                                                                   .    FI196_A .    Manure_Source .    BIOMASS_FLOW_MANURE 460500   
2030                                                                                                                   .    FI197_A .    Manure_Source .    BIOMASS_FLOW_MANURE 1034900  
2030                                                                                                                   .    FI1B1_A .    Manure_Source .    BIOMASS_FLOW_MANURE 949500   
2030                                                                                                                   .    FI1C1_A .    Manure_Source .    BIOMASS_FLOW_MANURE 424400   
2030                                                                                                                   .    FI1C2_A .    Manure_Source .    BIOMASS_FLOW_MANURE 157400   
2030                                                                                                                   .    FI1C3_A .    Manure_Source .    BIOMASS_FLOW_MANURE 181400   
2030                                                                                                                   .    FI1C4_A .    Manure_Source .    BIOMASS_FLOW_MANURE 161500   
2030                                                                                                                   .    FI1C5_A .    Manure_Source .    BIOMASS_FLOW_MANURE 118300   
2030                                                                                                                   .    FI1D1_A .    Manure_Source .    BIOMASS_FLOW_MANURE 210700   
2030                                                                                                                   .    FI1D2_A .    Manure_Source .    BIOMASS_FLOW_MANURE 345300   
2030                                                                                                                   .    FI1D3_A .    Manure_Source .    BIOMASS_FLOW_MANURE 229700   
2030                                                                                                                   .    FI1D4_A .    Manure_Source .    BIOMASS_FLOW_MANURE 105800   
2030                                                                                                                   .    FI1D5_A .    Manure_Source .    BIOMASS_FLOW_MANURE 95700    
2030                                                                                                                   .    FI1D6_A .    Manure_Source .    BIOMASS_FLOW_MANURE 567900   
2030                                                                                                                   .    FI1D7_A .    Manure_Source .    BIOMASS_FLOW_MANURE 252700   
2030                                                                                                                   .    FI200_A .    Manure_Source .    BIOMASS_FLOW_MANURE 13500    
2030                                                                                                                   .    FR_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 258705000
2030                                                                                                                   .    DE4-E_A .    Manure_Source .    BIOMASS_FLOW_MANURE 29100000 
2030                                                                                                                   .    DE4-N_A .    Manure_Source .    BIOMASS_FLOW_MANURE 9700000  
2030                                                                                                                   .    DE4-S_A .    Manure_Source .    BIOMASS_FLOW_MANURE 20400000 
2030                                                                                                                   .    DE4-W_A .    Manure_Source .    BIOMASS_FLOW_MANURE 43100000 
2030                                                                                                                   .    GR_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 7393000  
2030                                                                                                                   .    HU_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 62792000 
2030                                                                                                                   .    IE_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 18101000 
2030                                                                                                                   .    ITC_A   .    Manure_Source .    BIOMASS_FLOW_MANURE 62200000 
2030                                                                                                                   .    ITF_A   .    Manure_Source .    BIOMASS_FLOW_MANURE 6400000  
2030                                                                                                                   .    ITG_A   .    Manure_Source .    BIOMASS_FLOW_MANURE 3300000  
2030                                                                                                                   .    ITH_A   .    Manure_Source .    BIOMASS_FLOW_MANURE 39500000 
2030                                                                                                                   .    ITI_A   .    Manure_Source .    BIOMASS_FLOW_MANURE 8200000  
2030                                                                                                                   .    LV_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 7401000  
2030                                                                                                                   .    LT_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 12700000 
2030                                                                                                                   .    LU_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 1521900  
2030                                                                                                                   .    MT_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 407000   
2030                                                                                                                   .    ME_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 300000   
2030                                                                                                                   .    NL_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 48769000 
2030                                                                                                                   .    MK_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 703000   
2030                                                                                                                   .    NO020_A .    Manure_Source .    BIOMASS_FLOW_MANURE 22300    
2030                                                                                                                   .    NO060_A .    Manure_Source .    BIOMASS_FLOW_MANURE 27600    
2030                                                                                                                   .    NO071_A .    Manure_Source .    BIOMASS_FLOW_MANURE 14600    
2030                                                                                                                   .    NO072_A .    Manure_Source .    BIOMASS_FLOW_MANURE 10000    
2030                                                                                                                   .    NO073_A .    Manure_Source .    BIOMASS_FLOW_MANURE 4600     
2030                                                                                                                   .    NO081_A .    Manure_Source .    BIOMASS_FLOW_MANURE 40500    
2030                                                                                                                   .    NO083_A .    Manure_Source .    BIOMASS_FLOW_MANURE 18800    
2030                                                                                                                   .    NO084_A .    Manure_Source .    BIOMASS_FLOW_MANURE 43800    
2030                                                                                                                   .    NO085_A .    Manure_Source .    BIOMASS_FLOW_MANURE 16200    
2030                                                                                                                   .    NO092_A .    Manure_Source .    BIOMASS_FLOW_MANURE 18200    
2030                                                                                                                   .    NO093_A .    Manure_Source .    BIOMASS_FLOW_MANURE 15400    
2030                                                                                                                   .    NO094_A .    Manure_Source .    BIOMASS_FLOW_MANURE 10500    
2030                                                                                                                   .    NO0A1_A .    Manure_Source .    BIOMASS_FLOW_MANURE 28400    
2030                                                                                                                   .    NO0A2_A .    Manure_Source .    BIOMASS_FLOW_MANURE 37900    
2030                                                                                                                   .    NO0A3_A .    Manure_Source .    BIOMASS_FLOW_MANURE 37900    
2030                                                                                                                   .    PL_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 71160000 
2030                                                                                                                   .    PT_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 22088000 
2030                                                                                                                   .    RO_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 22816000 
2030                                                                                                                   .    RS_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 10502000 
2030                                                                                                                   .    SK_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 13701000 
2030                                                                                                                   .    SI_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 1448000  
2030                                                                                                                   .    ES_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 100580000
2030                                                                                                                   .    SE110_A .    Manure_Source .    BIOMASS_FLOW_MANURE 360500   
2030                                                                                                                   .    SE121_A .    Manure_Source .    BIOMASS_FLOW_MANURE 773000   
2030                                                                                                                   .    SE122_A .    Manure_Source .    BIOMASS_FLOW_MANURE 621700   
2030                                                                                                                   .    SE123_A .    Manure_Source .    BIOMASS_FLOW_MANURE 979400   
2030                                                                                                                   .    SE124_A .    Manure_Source .    BIOMASS_FLOW_MANURE 638300   
2030                                                                                                                   .    SE125_A .    Manure_Source .    BIOMASS_FLOW_MANURE 579700   
2030                                                                                                                   .    SE211_A .    Manure_Source .    BIOMASS_FLOW_MANURE 1749100  
2030                                                                                                                   .    SE212_A .    Manure_Source .    BIOMASS_FLOW_MANURE 960900   
2030                                                                                                                   .    SE213_A .    Manure_Source .    BIOMASS_FLOW_MANURE 1197000  
2030                                                                                                                   .    SE214_A .    Manure_Source .    BIOMASS_FLOW_MANURE 290900   
2030                                                                                                                   .    SE221_A .    Manure_Source .    BIOMASS_FLOW_MANURE 381500   
2030                                                                                                                   .    SE224_A .    Manure_Source .    BIOMASS_FLOW_MANURE 3189500  
2030                                                                                                                   .    SE231_A .    Manure_Source .    BIOMASS_FLOW_MANURE 708500   
2030                                                                                                                   .    SE232_A .    Manure_Source .    BIOMASS_FLOW_MANURE 3721700  
2030                                                                                                                   .    SE311_A .    Manure_Source .    BIOMASS_FLOW_MANURE 362100   
2030                                                                                                                   .    SE312_A .    Manure_Source .    BIOMASS_FLOW_MANURE 367600   
2030                                                                                                                   .    SE313_A .    Manure_Source .    BIOMASS_FLOW_MANURE 369100   
2030                                                                                                                   .    SE321_A .    Manure_Source .    BIOMASS_FLOW_MANURE 357400   
2030                                                                                                                   .    SE322_A .    Manure_Source .    BIOMASS_FLOW_MANURE 186400   
2030                                                                                                                   .    SE331_A .    Manure_Source .    BIOMASS_FLOW_MANURE 338300   
2030                                                                                                                   .    SE332_A .    Manure_Source .    BIOMASS_FLOW_MANURE 322400   
2030                                                                                                                   .    CH_A    .    Manure_Source .    BIOMASS_FLOW_MANURE 31728800 
2030                                                                                                                   .    UK_GB_A .    Manure_Source .    BIOMASS_FLOW_MANURE 139189000
2030                                                                                                                   .    UK_NI_A .    Manure_Source .    BIOMASS_FLOW_MANURE 18000000 
                                                                                                                                                                                         
/;                                                                                                                                                                                       
                                                                                                                                                                                         
*Manure                                                                                                                                                                                  
MAXFLOW('2035',AAA,'Manure_Source','BIOMASS_FLOW_MANURE') = MAXFLOW('2030',AAA,'Manure_Source','BIOMASS_FLOW_MANURE');                                                                   
MAXFLOW('2040',AAA,'Manure_Source','BIOMASS_FLOW_MANURE') = MAXFLOW('2030',AAA,'Manure_Source','BIOMASS_FLOW_MANURE');                                                                   
MAXFLOW('2045',AAA,'Manure_Source','BIOMASS_FLOW_MANURE') = MAXFLOW('2030',AAA,'Manure_Source','BIOMASS_FLOW_MANURE');                                                                   
MAXFLOW('2050',AAA,'Manure_Source','BIOMASS_FLOW_MANURE') = MAXFLOW('2030',AAA,'Manure_Source','BIOMASS_FLOW_MANURE');                                                                   
                                                                                                                                                                                         
*Limit on fossil CO2 in fuel production after 2030                                                                                                                                       
*MAXFLOW('2040',AAAOPTIFLOW,'CO2_CU','CO2_FLOW_FOSSIL')=EPS;                                                                                                                             
*MAXFLOW('2050',AAAOPTIFLOW,'CO2_CU','CO2_FLOW_FOSSIL')=EPS;                                                                                                                             
                                                                                                                                                                                         
*Limit renewable fuel OCC in 2030                                                                                                                                                        
MAXFLOW('2030',AAAOPTIFLOW,'Biooil_Eff_OCC','BIOOIL_OCC_FLOW')=EPS;                                                                                                                      
MAXFLOW('2030',AAAOPTIFLOW,'EFT_Diesel_Eff_OCC','EDIESEL_OCC_FLOW')=EPS;                                                                                                                 
MAXFLOW('2030',AAAOPTIFLOW,'LBG_Eff_OCC','LBG_OCC_FLOW')=EPS;                                                                                                                            
