SET PROCTECHTYPE(PROC,TECH_GROUP)                                  
                                                                   
/                                                                  
CO2_DAC_20                        .    DAC_Y                       
CO2_DAC_25                        .    DAC_Y                       
CO2_DAC_30                        .    DAC_Y                       
CO2_DAC_35                        .    DAC_Y                       
CO2_DAC_40                        .    DAC_Y                       
CO2_DAC_45                        .    DAC_Y                       
CO2_DAC_50                        .    DAC_Y                       
Transport_Pipeline_CO2            .    Transport_Pipeline_CO2      
OCC_30                            .    OCC_Y                       
OCC_35                            .    OCC_Y                       
OCC_40                            .    OCC_Y                       
OCC_45                            .    OCC_Y                       
OCC_50                            .    OCC_Y                       
CO2_Seq_On_20                     .    Seq_On_Y                    
CO2_Seq_On_25                     .    Seq_On_Y                    
CO2_Seq_On_30                     .    Seq_On_Y                    
CO2_Seq_On_35                     .    Seq_On_Y                    
CO2_Seq_On_40                     .    Seq_On_Y                    
CO2_Seq_On_45                     .    Seq_On_Y                    
CO2_Seq_On_50                     .    Seq_On_Y                    
CO2_Seq_Off_20                    .    Seq_Off_Y                   
CO2_Seq_Off_25                    .    Seq_Off_Y                   
CO2_Seq_Off_30                    .    Seq_Off_Y                   
CO2_Seq_Off_35                    .    Seq_Off_Y                   
CO2_Seq_Off_40                    .    Seq_Off_Y                   
CO2_Seq_Off_45                    .    Seq_Off_Y                   
CO2_Seq_Off_50                    .    Seq_Off_Y                   
Digestion_Tank_Manure_20          .    Digestion_Tank_Manure_Y     
Digestion_Tank_Manure_25          .    Digestion_Tank_Manure_Y     
Digestion_Tank_Manure_30          .    Digestion_Tank_Manure_Y     
Digestion_Tank_Manure_35          .    Digestion_Tank_Manure_Y     
Digestion_Tank_Manure_40          .    Digestion_Tank_Manure_Y     
Digestion_Tank_Manure_45          .    Digestion_Tank_Manure_Y     
Digestion_Tank_Manure_50          .    Digestion_Tank_Manure_Y     
Digestion_Tank_Straw_20           .    Digestion_Tank_Straw_Y      
Digestion_Tank_Straw_25           .    Digestion_Tank_Straw_Y      
Digestion_Tank_Straw_30           .    Digestion_Tank_Straw_Y      
Digestion_Tank_Straw_35           .    Digestion_Tank_Straw_Y      
Digestion_Tank_Straw_40           .    Digestion_Tank_Straw_Y      
Digestion_Tank_Straw_45           .    Digestion_Tank_Straw_Y      
Digestion_Tank_Straw_50           .    Digestion_Tank_Straw_Y      
Methanation_20                    .    Methanation_Y               
Methanation_25                    .    Methanation_Y               
Methanation_30                    .    Methanation_Y               
Methanation_35                    .    Methanation_Y               
Methanation_40                    .    Methanation_Y               
Methanation_45                    .    Methanation_Y               
Methanation_50                    .    Methanation_Y               
Biogas_Upgrading_20               .    Biogas_Upgrading_Y          
Biogas_Upgrading_25               .    Biogas_Upgrading_Y          
Biogas_Upgrading_30               .    Biogas_Upgrading_Y          
Biogas_Upgrading_35               .    Biogas_Upgrading_Y          
Biogas_Upgrading_40               .    Biogas_Upgrading_Y          
Biogas_Upgrading_45               .    Biogas_Upgrading_Y          
Biogas_Upgrading_50               .    Biogas_Upgrading_Y          
Pyrolysis_Straw_25                .    Pyrolysis_Y                 
Pyrolysis_Straw_30                .    Pyrolysis_Y                 
Pyrolysis_Straw_35                .    Pyrolysis_Y                 
Pyrolysis_Straw_40                .    Pyrolysis_Y                 
Pyrolysis_Straw_45                .    Pyrolysis_Y                 
Pyrolysis_Straw_50                .    Pyrolysis_Y                 
TG_20                             .    TG_Y                        
TG_25                             .    TG_Y                        
TG_30                             .    TG_Y                        
TG_35                             .    TG_Y                        
TG_40                             .    TG_Y                        
TG_45                             .    TG_Y                        
TG_50                             .    TG_Y                        
Methanol_synthesis_TG_20          .    Methanol_TG_Y               
Methanol_synthesis_TG_25          .    Methanol_TG_Y               
Methanol_synthesis_TG_30          .    Methanol_TG_Y               
Methanol_synthesis_TG_35          .    Methanol_TG_Y               
Methanol_synthesis_TG_40          .    Methanol_TG_Y               
Methanol_synthesis_TG_45          .    Methanol_TG_Y               
Methanol_synthesis_TG_50          .    Methanol_TG_Y               
Methanol_synthesis_biogas_20      .    Methanol_Biogas_Y           
Methanol_synthesis_biogas_25      .    Methanol_Biogas_Y           
Methanol_synthesis_biogas_30      .    Methanol_Biogas_Y           
Methanol_synthesis_biogas_35      .    Methanol_Biogas_Y           
Methanol_synthesis_biogas_40      .    Methanol_Biogas_Y           
Methanol_synthesis_biogas_45      .    Methanol_Biogas_Y           
Methanol_synthesis_biogas_50      .    Methanol_Biogas_Y           
EMethanol_synthesis_20            .    EMethanol_Y                 
EMethanol_synthesis_25            .    EMethanol_Y                 
EMethanol_synthesis_30            .    EMethanol_Y                 
EMethanol_synthesis_35            .    EMethanol_Y                 
EMethanol_synthesis_40            .    EMethanol_Y                 
EMethanol_synthesis_45            .    EMethanol_Y                 
EMethanol_synthesis_50            .    EMethanol_Y                 
Methanol_Upgrade_20               .    Methanol_Upgrade_Y          
Methanol_Upgrade_25               .    Methanol_Upgrade_Y          
Methanol_Upgrade_30               .    Methanol_Upgrade_Y          
Methanol_Upgrade_35               .    Methanol_Upgrade_Y          
Methanol_Upgrade_40               .    Methanol_Upgrade_Y          
Methanol_Upgrade_45               .    Methanol_Upgrade_Y          
Methanol_Upgrade_50               .    Methanol_Upgrade_Y          
Ammonia_Synthesis_20              .    Ammonia_Y                   
Ammonia_Synthesis_25              .    Ammonia_Y                   
Ammonia_Synthesis_30              .    Ammonia_Y                   
Ammonia_Synthesis_35              .    Ammonia_Y                   
Ammonia_Synthesis_40              .    Ammonia_Y                   
Ammonia_Synthesis_45              .    Ammonia_Y                   
Ammonia_Synthesis_50              .    Ammonia_Y                   
BioFT_20                          .    BioFT_Y                     
BioFT_25                          .    BioFT_Y                     
BioFT_30                          .    BioFT_Y                     
BioFT_35                          .    BioFT_Y                     
BioFT_40                          .    BioFT_Y                     
BioFT_45                          .    BioFT_Y                     
BioFT_50                          .    BioFT_Y                     
BioFT_H2_20                       .    BioFT_H2_Y                  
BioFT_H2_25                       .    BioFT_H2_Y                  
BioFT_H2_30                       .    BioFT_H2_Y                  
BioFT_H2_35                       .    BioFT_H2_Y                  
BioFT_H2_40                       .    BioFT_H2_Y                  
BioFT_H2_45                       .    BioFT_H2_Y                  
BioFT_H2_50                       .    BioFT_H2_Y                  
EFT_20                            .    EFT_Y                       
EFT_25                            .    EFT_Y                       
EFT_30                            .    EFT_Y                       
EFT_35                            .    EFT_Y                       
EFT_40                            .    EFT_Y                       
EFT_45                            .    EFT_Y                       
EFT_50                            .    EFT_Y                       
/;                                                                 
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
                                                                   
