SET PROCSINK(PROC) "End PROC (no trace leaving it)"
/                                                  
                                                   
CO2_Seq_Buffer                                     
CO2_Biochar_Buffer                                 
Money_buffer_T                                     
CO2_Sink                                           
CO2_Neg_Sink                                       
Shipping_Buffer_Long                               
Shipping_Buffer_Medium                             
Shipping_Buffer_Legacy                             
Shipping_Buffer_Tanker                             
Shipping_Buffer_Short                              
Road_Buffer                                        
Aviation_Buffer                                    
                                                   
Fuel_Price_Raw                                     
Fuel_Price_Long                                    
Fuel_Price_Medium                                  
Fuel_Price_Short                                   
Fuel_Price_Legacy                                  
Fuel_Price_Tanker                                  
                                                   
Retrofit_Buffer                                    
OCC_Buffer                                         
Fuel_Ramping_Buffer                                
                                                   
/;                                                 
