SET PROCEXIM(PROC) "PROC for exchange possibility between areas AAA"
/                                                                   
*Liquid hydrocarbons (LHC)                                          
Transport_Truck_LHC                                                 
Transport_Ship_LHC                                                  
                                                                    
*Ammonia                                                            
Transport_Truck_Ammonia                                             
Transport_Ship_Ammonia                                              
                                                                    
*Methanol                                                           
Transport_Truck_Methanol                                            
Transport_Ship_Methanol                                             
                                                                    
*CO2                                                                
Transport_Pipeline_CO2                                              
Transport_Truck_CO2                                                 
Transport_Ship_CO2                                                  
                                                                    
*Biomass                                                            
Transport_Truck_Wood                                                
Transport_Truck_Straw                                               
/;                                                                  
