PARAMETER PROCEXIM_ENDO_FUEL(PROC, FLOW) 'Subset of (PROCEXIM,FLOWEXIM) where onboard fuel use is endogenised as relative efficiency loss'                                       
/                                                                                                                                                                                
                                                                                                                                                                                 
Transport_Ship_LHC                                                                                                                         .    EJET_FLOW     6.896059951582E-006
Transport_Ship_LHC                                                                                                                         .    BIOJET_FLOW   6.896059951582E-006
Transport_Ship_Methanol                                                                                                                    .    METHANOL_FLOW 9.227507119579E-006
Transport_Ship_Ammonia                                                                                                                     .    AMMONIA_FLOW  2.264809371484E-005
                                                                                                                                                                                 
/;                                                                                                                                                                               
                                                                                                                                                                                 
                                                                                                                                                                                 
                                                                                                                                                                                 
                                                                                                                                                                                 
                                                                                                                                                                                 
                                                                                                                                                                                 
                                                                                                                                                                                 
                                                                                                                                                                                 
