SET TECH_GROUP "Technology Groups"
                                  
/                                 
CO2_Comp                          
DAC_Y                             
Pipeline_CO2_Group                
Seq_On_Y                          
Seq_Off_Y                         
Digestion_Tank_Manure_Y           
Digestion_Tank_Straw_Y            
Methanation_Y                     
Biogas_Upgrading_Y                
Biogas_Liquefaction_Y             
Pyrolysis_Y                       
TG_Y                              
Hydrogen_Liquefaction_Y           
Methanol_TG_Y                     
Methanol_Biogas_Y                 
EMethanol_Y                       
Methanol_Upgrade_Y                
Ammonia_Y                         
BioFT_Y                           
BioFT_H2_Y                        
EFT_Y                             
Ship_Capacity                     
/;                                
