SET PROCEXIM(PROC) "PROC for exchange possibility between areas AAA"
/                                                                   
ProcEximTruck                                                       
ProcEximShip                                                        
Exim_CO2_Pipeline                                                   
                                                                    
/;                                                                  
