SET PROCSINK(PROC) "End PROC (no trace leaving it)"
/                                                  
Aviation_Buffer                                    
CO2_Seq_Buffer                                     
CO2_Biochar_Buffer                                 
Money_buffer_T                                     
Road_Buffer                                        
Shipping_Buffer                                    
/;                                                 
