SET TECH_GROUP "Technology Groups"
                                  
/                                 
DAC_Y                             
Transport_Pipeline_CO2            
OCC_Y                             
Seq_On_Y                          
Seq_Off_Y                         
Digestion_Tank_Manure_Y           
Digestion_Tank_Straw_Y            
Methanation_Y                     
Biogas_Upgrading_Y                
Pyrolysis_Y                       
TG_Y                              
Methanol_TG_Y                     
Methanol_Biogas_Y                 
EMethanol_Y                       
Methanol_Upgrade_Y                
Ammonia_Y                         
BioFT_Y                           
BioFT_H2_Y                        
EFT_Y                             
/;                                
