SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                                                                                                                    
S08,S22,S36,S50                                                                                
/;                                                                                             
